package com.wechantloup.spritehandler.spriteCreation

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.toArgb
import com.wechantloup.spritehandler.composeElement.dialog.ClosedDialogState
import com.wechantloup.spritehandler.composeElement.dialog.DialogState
import com.wechantloup.spritehandler.model.Image

internal data class SpriteCreationState(
    val folderName: String = "",
    val images: List<Image> = emptyList(),
    val autoGeneratedPalette: Boolean = true,
    val palette: List<Int> = initPalette(),
    val dialog: DialogState = ClosedDialogState,
) {
    val selectedImageCount: Int
        get() = images.filter { it.isSelected }.size

    companion object {
        private fun initPalette(): List<Int> {
            return mutableListOf<Int>().apply {
                repeat(15) {
                    add(Color.Unspecified.toArgb())
                }
            }
        }
    }
}
