package com.wechantloup.spritehandler.useCase

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.decodeToImageBitmap
import androidx.compose.ui.graphics.toArgb
import androidx.compose.ui.graphics.toPixelMap
import com.wechantloup.spritehandler.model.Image
import com.wechantloup.spritehandler.model.Palette
import com.wechantloup.spritehandler.model.SpriteAlignment
import java.io.File
import java.util.logging.Logger

object SpriteUseCase {
    private val logger = Logger.getLogger("SpriteUseCase")

    fun getPalette(
        autoGenerated: Boolean,
        images: List<Image>,
        selectedColors: List<Int>,
    ): Palette {
        return if (autoGenerated) {
            generatePalette(images)
        } else {
            checkPalette(images, selectedColors)
        }
    }

    fun generateSprite(
        images: List<Image>,
        palette: Palette,
        width: Int,
        height: Int,
        alignment: SpriteAlignment,
    ): List<Int> {
        val images = images.filter { it.isSelected }

        val pixels: List<Int> = images.flatMap { image ->
            val bitmap = File(image.path)
                .inputStream()
                .readAllBytes()
                .decodeToImageBitmap()

            val pixelMap = bitmap.toPixelMap()

            val offsetX = when (alignment) {
                SpriteAlignment.TOP_LEFT,
                SpriteAlignment.CENTER_LEFT,
                SpriteAlignment.BOTTOM_LEFT   -> 0
                SpriteAlignment.TOP_CENTER,
                SpriteAlignment.CENTER,
                SpriteAlignment.BOTTOM_CENTER -> (width - image.width) / 2
                SpriteAlignment.TOP_RIGHT,
                SpriteAlignment.CENTER_RIGHT,
                SpriteAlignment.BOTTOM_RIGHT  -> width - image.width
            }

            val offsetY = when (alignment) {
                SpriteAlignment.TOP_LEFT,
                SpriteAlignment.TOP_CENTER,
                SpriteAlignment.TOP_RIGHT     -> 0
                SpriteAlignment.CENTER_LEFT,
                SpriteAlignment.CENTER,
                SpriteAlignment.CENTER_RIGHT  -> (height - image.height) / 2
                SpriteAlignment.BOTTOM_LEFT,
                SpriteAlignment.BOTTOM_CENTER,
                SpriteAlignment.BOTTOM_RIGHT  -> height - image.height
            }

            List(width * height) { index ->
                val outX = index % width
                val outY = index / width

                val imgX = outX - offsetX
                val imgY = outY - offsetY

                if (imgX < 0 || imgX >= image.width || imgY < 0 || imgY >= image.height) {
                    0 // zone vide → couleur transparente
                } else {
                    val color = pixelMap[imgX, imgY]
                    palette.colors.indexOf(color.toArgb())
                }
            }
        }

        return pixels
    }

    fun encode(
        width: Int,
        height: Int,
        palette: Palette,
        imageCount: Int,
        pixelColors: List<Int>,
    ): List<Byte> {
        val bytes = mutableListOf<Byte>()

        bytes.add(0.toByte())

        if (width > 255) throw IllegalStateException("width must be 255 or less")
        bytes.add(width.toByte())
        if (height > 255) throw IllegalStateException("height must be 255 or less")
        bytes.add(height.toByte())

        palette.colors.forEach { color ->
            val colorBytes = color.toBytes()
            bytes.addAll(colorBytes)
        }

        if (imageCount > 255) throw IllegalStateException("Can't have more than 255 images")
        bytes.add(imageCount.toByte())

        val pixelBytes = pixelColors.toPackedBytes()
        bytes.addAll(pixelBytes)

        return bytes
    }

    private fun generatePalette(images: List<Image>): Palette {
//        logger.info("generatePalette")
        val colors = mutableListOf(Color.Transparent.toArgb())

        images.forEach { image ->
            val bitmap = File(image.path)
                .inputStream()
                .readAllBytes()
                .decodeToImageBitmap()

            val pixelMap = bitmap.toPixelMap()

            for (i in 0 until image.width) {
                for (j in 0 until image.height) {
                    val color = pixelMap[i, j]
//                    if (color.alpha > 0f && color.alpha < 1f) {
//                        logger.info("Semi-transparent at ($i,$j) : alpha=${color.alpha} color=$color")
//                    }
                    val argbColor = //if (color.alpha == 1f) {
                        color.toArgb()
//                    } else {
//                        Color.Transparent.value
//                    }
                    if (!colors.contains(argbColor)) {
//                        logger.info("new color found $color")
                        colors.add(argbColor)
                    }
                }
            }
        }

//        logger.info("${colors.size} color found")
        if (colors.size > 16) throw IllegalStateException("Too many colors")

        if (colors.size < 16) {
            (colors.size until 16).forEach { _ ->
                colors.add(Color.Unspecified.toArgb())
            }
        }

        return Palette(colors)
    }

    private fun checkPalette(images: List<Image>, colorList: List<Int>): Palette {
        val colors = colorList
            .toMutableList()
            .apply { add(0, Color.Transparent.toArgb()) }
        images.forEach { image ->
            val bitmap = File(image.path)
                .inputStream()
                .readAllBytes()
                .decodeToImageBitmap()

            val pixelMap = bitmap.toPixelMap()

            for (i in 0 until image.width) {
                for (j in 0 until image.height) {
                    val color = pixelMap[i, j]
                    if (color.alpha == 1f) {
                        val argbColor = color.toArgb()
                        if (!colors.contains(argbColor)) {
                            throw IllegalStateException("Missing color $color in palette")
                        }
                    }
                }
            }
        }
        return Palette(colors)
    }

    private fun Int.toBytes(): List<Byte> = (3 downTo 0).map { i ->
        ((this shr (i * 8)) and 0xFF).toByte()
    }

    private fun List<Byte>.toInt(): Int = fold(0) { acc, byte ->
        (acc shl 8) or (byte.toInt() and 0xFF)
    }

    private fun List<Int>.toPackedBytes(): List<Byte> = chunked(2).map { chunk ->
        val high = chunk[0] and 0xF
        val low = if (chunk.size == 2) chunk[1] and 0xF else 0
        ((high shl 4) or low).toByte()
    }

    private fun List<Byte>.toNibbles(originalSize: Int): List<Int> = flatMap { byte ->
        val high = (byte.toInt() shr 4) and 0xF
        val low = byte.toInt() and 0xF
        listOf(high, low)
    }.take(originalSize)
}
